export const pagesList = [
    {
        id: 1,
        name: 'Github Repo',
        desc: 'Приложение для загрузки репозиториев пользователей с Github.',
        tech: 'React, render props, MomentJS, Axios, createPortal, media tags',
        link: '/github-repo',
    },
    {
        id: 2,
        name: 'JSON Placeholder',
        desc: 'Приложение, которое загружает списки с сайта JSON Placeholder',
        tech: 'React, Redux, Redux Toolkit, react-transition-group',
        link: '/json-placeholder',
    },
    {
        id: 3,
        name: 'The Impulse Demo',
        desc: 'Небольшая браузерная логическая игра, в которой нужно перемещаться между квадратами в соответствии с цветовыми схемами.',
        tech: 'React, Redux, Middleware, Redux Thunk, TypeScript, SCSS',
        link: '/the-impulse',
    },
    {
        id: 4,
        name: 'Quiz',
        desc: 'Игра "Викторина". 10 вопросов с таймером. Таблица рекордов.',
        tech: 'React, createPortal, local storage, Styled-components, Lodash',
        link: '/quiz',
    },
    {
        id: 5,
        name: 'Lodash Sandbox',
        desc: 'Эксперименты с Lodash',
        tech: 'Lodash',
        link: '/lodash',
    },
    {
        id: 6,
        name: 'MomentJS Sandbox',
        desc: 'Эксперименты с MomentJS',
        tech: 'MomentJS',
        link: '/moment',
    },
    {
        id: 7,
        name: 'Todo',
        desc: 'Приложение для ведения списка дел. Использует матрицу Эйзенхауэра для эффективного решения задач.',
        tech: 'React, Storybook, Styled components, local storage, css grid, TypeScript',
        link: '/todo',
    },
    {
        id: 8,
        name: 'Render Props',
        desc: 'Тренировка render props',
        tech: 'React, render props',
        link: '/render-props',
    },
]
